openapi: 3.0.2
info:
  title: Petstore API
  version: 2.0.0
  description: |-
    A sample API that uses a petstore as an example to demonstrate features
    in the OpenAPI 3.0 specification and Microcks
  contact:
    name: Microcks Team
    url: 'https://microcks.io'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - properties:
            id:
              format: int64
              type: integer
          required:
            - id
    NewPet:
      properties:
        name:
          type: string
        coat:
          $ref: '#/components/schemas/Coat'
        bugs:
          type: array
          items:
            $ref: '#/components/schemas/Bug'
      required:
          - name
    Coat:
      type: object
      properties:
        name:
          type: string
        tint:
          type: string
          enum:
            - light
            - dark
      required:
        - name
    Bug:
      type: string
      enum:
        - tick
        - flea
paths:
  /my/pets:
    get:
      description: A list of pets owned by the user
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                my_pets:
                  value:
                    - id: 1
                      name: Zaza
                      coat:
                        name: merle
                        tint: light
                    - id: 2
                      name: Tigresse
                      coat:
                        name: tabby
                        tint: dark
                    - id: 3
                      name: Maki
                      coat:
                        name: calico
                        tint: dark
                    - id: 4
                      name: Toufik
                      coat:
                        name: tabby
                        tint: dark
  /pets:
    get:
      description: A list of all pets filtered by name
      parameters:
        - name: filter
          in: query
          schema:
            type: string
          examples:
            k_pets:
              value: k  
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                k_pets:
                  value:
                    - id: 3
                      name: Maki
                      coat:
                        name: calico
                        tint: dark
                    - id: 4
                      name: Toufik
                      coat:
                        name: tabby
                        tint: dark
    post:
      summary: Add a new pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
            examples:
              new_pet:
                value:
                  name: Jojo
                  coat:
                    name: tabby
                    tint: light
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              examples:
                new_pet:
                  value: |-
                    {
                      "id": {{ randomInt(5,10) }},
                      "name": "{{ request.body/name }}"
                    }
  /pets/{id}:
    get:
      description: Get a pet by its ID
      parameters:
        - name: id
          in: path
          schema:
            type: string
          examples:
            pet_1:
              value: '1'
            pet_2:
              value: '2'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              examples:
                pet_1:
                  value:
                    id: 1
                    name: Zaza
                    coat:
                      name: merle
                      tint: light
                pet_2:
                  value:
                    id: 2
                    name: Tigresse
                    coat:
                      name: tabby
                      tint: dark